version: "3.9"
services:
  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "kwacker"
      POSTGRES_USER: "kwacker"
      POSTGRES_PASSWORD: "1234"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./migrations/initilize.sql:/docker-entrypoint-initdb.d/initilize.sql
      - kwacker-pg-data:/var/lib/postgresql/data
      - /var/run/postgresql/:/var/run/postgresql
    ports:
      - "5432:5432"

volumes:
  kwacker-pg-data:
